#!/usr/bin/env bash
# install-hooks.sh — install git hooks for the demo vault
#
# Creates a wrapper at .git/hooks/pre-commit (not versioned, but where
# the health check looks) that delegates to the versioned hook in
# .githooks/.
#
# NOTE: there is deliberately NO post-commit hook. The pre-commit
# regenerates indexes and stages them BEFORE the commit, so the working
# tree stays clean. A post-commit that rewrites files would leave
# uncommitted changes right after every commit — that is an anti-pattern.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"

mkdir -p "$HOOKS_DIR"

cat > "$HOOKS_DIR/pre-commit" <<EOF
#!/usr/bin/env bash
# Generated by scripts/install-hooks.sh — delegates to versioned hook.
exec "$REPO_ROOT/.githooks/pre-commit" "\$@"
EOF
chmod +x "$HOOKS_DIR/pre-commit"

# Remove a stale post-commit wrapper if one exists (from older installs).
if [ -f "$HOOKS_DIR/post-commit" ]; then
  rm -f "$HOOKS_DIR/post-commit"
  echo "  removed stale .git/hooks/post-commit"
fi

echo "✅ git hooks installed"
echo "   .git/hooks/pre-commit -> .githooks/pre-commit (validate + index, staged before commit)"
echo "   No post-commit hook — working tree stays clean after commits"
echo "   Requires: pip install mcp-okf  (provides python3 -m cli)"
