#!/usr/bin/env bash
# install-hooks.sh — install git hooks for the demo vault
#
# Creates a wrapper at .git/hooks/pre-commit (not versioned, but where
# the health check looks) that delegates to the versioned hook in
# .githooks/. Same for post-commit.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"

mkdir -p "$HOOKS_DIR"

for hook in pre-commit post-commit; do
  cat > "$HOOKS_DIR/$hook" <<EOF
#!/usr/bin/env bash
# Generated by scripts/install-hooks.sh — delegates to versioned hook.
exec "$REPO_ROOT/.githooks/$hook" "\$@"
EOF
  chmod +x "$HOOKS_DIR/$hook"
done

echo "✅ git hooks installed"
echo "   .git/hooks/pre-commit  -> .githooks/pre-commit  (validate + index)"
echo "   .git/hooks/post-commit -> .githooks/post-commit (index)"
echo "   Requires: pip install mcp-okf  (provides python3 -m cli)"
